/**
 * 
 */
package com.anthavio.kitty.vaadin;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.Property;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.RichTextArea;

/**
 * @author vanek
 *
 */
public class DocumentEditor extends CustomComponent {

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private Button save;
	@AutoGenerated
	private RichTextArea editor;

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public DocumentEditor(Property document) {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		editor.setPropertyDataSource(document);
		editor.setWriteThrough(false);
		save.addListener(new Button.ClickListener() {

			@Override
			public void buttonClick(ClickEvent event) {
				editor.commit();
				getApplication().getMainWindow().removeWindow(getWindow());//close popup
			}
		});
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);

		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");

		// editor
		editor = new RichTextArea();
		editor.setImmediate(false);
		editor.setWidth("100.0%");
		editor.setHeight("100.0%");
		mainLayout.addComponent(editor, "top:20.0px;right:20.0px;bottom:40.0px;left:20.0px;");

		// save
		save = new Button();
		save.setCaption("Save");
		save.setImmediate(false);
		save.setWidth("-1px");
		save.setHeight("-1px");
		mainLayout.addComponent(save, "top:434.0px;left:484.0px;");

		return mainLayout;
	}

}
