--DROP TABLE IF EXISTS SCENARIO_EXECUTION;

CREATE SEQUENCE IF NOT EXISTS SEQ_SCENARIO_EXECUTION START WITH 1 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS SCENARIO_EXECUTION (
	id INTEGER NOT NULL DEFAULT NEXTVAL('SEQ_SCENARIO_EXECUTION') PRIMARY KEY, 
	FILE_PATH VARCHAR(1000) NOT NULL, 
	START_TS TIMESTAMP NOT NULL,
	END_TS TIMESTAMP,
	ERR_STEP VARCHAR(1000),
	ERR_MSG VARCHAR(4000),
);